export const data = [
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
    },
]