export const data = [
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
        description: "Barbie and Oppenheimer open on the same weekend, which is great for both films and cinema in general.",
        genre: "Film",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
        description: "Once we’ve learned how to do something, we become “unconsciously competent” at it. In order to break with the predictable path and move forward, what my good friend and colleague,",
        genre: "Rita McGrath",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
        description: "Why I Can’t Forget This Poem",
        genre: "Poetry",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
        description: "From the present day all the way to less than 400 million years after the Big Bang, we’re seeing how the Universe grew up like never before.",
        genre: "NASA",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
        description: "I wrote a letter thanking librarians across the country for everything they’re doing to protect our freedom to read.",
        genre: "",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
        description: "Barbie and Oppenheimer open on the same weekend, which is great for both films and cinema in general.",
        genre: "Film",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
        description: "Once we’ve learned how to do something, we become “unconsciously competent” at it. In order to break with the predictable path and move forward, what my good friend and colleague,",
        genre: "Rita McGrath",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
        description: "Why I Can’t Forget This Poem",
        genre: "Poetry",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
        description: "From the present day all the way to less than 400 million years after the Big Bang, we’re seeing how the Universe grew up like never before.",
        genre: "NASA",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
        description: "I wrote a letter thanking librarians across the country for everything they’re doing to protect our freedom to read.",
        genre: "",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
        description: "Barbie and Oppenheimer open on the same weekend, which is great for both films and cinema in general.",
        genre: "Film",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
        description: "Once we’ve learned how to do something, we become “unconsciously competent” at it. In order to break with the predictable path and move forward, what my good friend and colleague,",
        genre: "Rita McGrath",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
        description: "Why I Can’t Forget This Poem",
        genre: "Poetry",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
        description: "From the present day all the way to less than 400 million years after the Big Bang, we’re seeing how the Universe grew up like never before.",
        genre: "NASA",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
        description: "I wrote a letter thanking librarians across the country for everything they’re doing to protect our freedom to read.",
        genre: "",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
        description: "Barbie and Oppenheimer open on the same weekend, which is great for both films and cinema in general.",
        genre: "Film",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
        description: "Once we’ve learned how to do something, we become “unconsciously competent” at it. In order to break with the predictable path and move forward, what my good friend and colleague,",
        genre: "Rita McGrath",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
        description: "Why I Can’t Forget This Poem",
        genre: "Poetry",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
        description: "From the present day all the way to less than 400 million years after the Big Bang, we’re seeing how the Universe grew up like never before.",
        genre: "NASA",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
        description: "I wrote a letter thanking librarians across the country for everything they’re doing to protect our freedom to read.",
        genre: "",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
        description: "Barbie and Oppenheimer open on the same weekend, which is great for both films and cinema in general.",
        genre: "Film",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
        description: "Once we’ve learned how to do something, we become “unconsciously competent” at it. In order to break with the predictable path and move forward, what my good friend and colleague,",
        genre: "Rita McGrath",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
        description: "Why I Can’t Forget This Poem",
        genre: "Poetry",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
        description: "From the present day all the way to less than 400 million years after the Big Bang, we’re seeing how the Universe grew up like never before.",
        genre: "NASA",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
        description: "I wrote a letter thanking librarians across the country for everything they’re doing to protect our freedom to read.",
        genre: "",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*7iOld74WIh9PHiLynIkOmw.png",
        author: "Simon Dillon",
        title: "Why I Love “Barbenheimer”",
        date: "Jul 10",
        duration: "5 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*rCypNw9YHdvjK_IC",
        description: "Barbie and Oppenheimer open on the same weekend, which is great for both films and cinema in general.",
        genre: "Film",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*46_J6xXhSeiqfW8HrtxK-g.png",
        author: "Rita McGrath",
        title: "Thinking Wrong: How to Trick our Brains into Being More Innovative",
        date: "Jul 13",
        duration: "6 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/0*tVRSDkvkjCr2Znry.png",
        description: "Once we’ve learned how to do something, we become “unconsciously competent” at it. In order to break with the predictable path and move forward, what my good friend and colleague,",
        genre: "Rita McGrath",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*NMZ_0Q7PLHu9KRpDvoxNMw.png",
        author: "Elin Dieme",
        title: "How Sylvia Plath’s “The Fig Tree” Changed My Perspective on Life",
        date: "Jun 17",
        duration: "11 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*6xpQuWk6zoE1mEjjD8SiEA.png",
        description: "Why I Can’t Forget This Poem",
        genre: "Poetry",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*VH9usPh601npohqlvpnxvg.jpeg",
        author: "Ethan Siegel",
        title: "NASA’s deepest 3D fly-through of the Universe",
        date: "Jul 19",
        duration: "10 min",
        image: "https://miro.medium.com/v2/da:true/resize:fill:200:200/1*TYdVeITHIFR8TWyX5j8cHA.gif",
        description: "From the present day all the way to less than 400 million years after the Big Bang, we’re seeing how the Universe grew up like never before.",
        genre: "NASA",
    },
    {
        author_image: "https://miro.medium.com/v2/resize:fill:40:40/1*AwBz4NW9_M45J-sBlmH-lA.png",
        author: "Barack Obama",
        title: "Thank You to America’s Librarians for Protecting Our Freedom to Read",
        date: "Jul 17",
        duration: "4 min",
        image: "https://miro.medium.com/v2/resize:fill:200:200/1*CvRhWlxwXZr39R1O0pA9PA.png",
        description: "I wrote a letter thanking librarians across the country for everything they’re doing to protect our freedom to read.",
        genre: "",
    },
]